# Generated by Django 4.1.4 on 2023-02-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('from_to', models.CharField(max_length=100)),
                ('froms', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('number', models.BigIntegerField()),
                ('sit_nmuber', models.IntegerField()),
            ],
        ),
    ]
